### ISSUE TITLE
I would like to have another webpage that test the adblocking DNS servers.

### ISSUE THREAD

**Issue by lostcowboy** [BrainicHQ/DoHSpeedTest#1]
I have been impressed with your webpage would it be possible to create a second webpage that tests the ad-blocking and malware-blocking DNS servers for speed? AdGuard has a list of some here. [https://adguard-dns.io/kb/general/dns-providers/](url)

**Comment by s1lviu** [comment]
> I have been impressed with your webpage would it be possible to create a second webpage that tests the ad-blocking and malware-blocking DNS servers for speed? AdGuard has a list of some here. [https://adguard-dns.io/kb/general/dns-providers/](url)

Hello @lostcowboy,
When I'll have some time, I will try to add the family and security endpoints too. 
Thanks.
