### ISSUE TITLE
[Feature Request] Could be helpful to include a column for mean/average time alongside the median.

### ISSUE THREAD

**Issue by AyoungDukie** [BrainicHQ/DoHSpeedTest#2]
Both median and average of a data set can be helpful to get an idea about any skew in data, so it could be helpful to include a column for mean/average time alongside the median.

Overall great work, and thanks for sharing this project!

**Comment by s1lviu** [comment]
Solved on https://github.com/BrainicHQ/DoHSpeedTest/pull/8
