### ISSUE TITLE
Recommend

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [BrainicHQ/DoHSpeedTest#9]
Auto conduct multiple tests and recommend the best dns server so that we dont have to analyze them after multiple tets oursleves

**Comment by ALMIGHTY-VC** [comment]
I love your project its just highlights how underrated dna are they are a space free way to optimize our internet

**Comment by ALMIGHTY-VC** [comment]
Or atleast Arranging their values in descending order

**Comment by s1lviu** [comment]
Thanks, the project is open for contributions and pull requests.
